apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ubpmc85r7-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:6aada67e6e5e7863dd1a21caf9c7a9dc8a0249cc@sha256:b0d8d911b9c2717a0f93ff0f7fcc85243254492d6fcdc5ee8b74911667233e8b
          name: container-image
