apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ubpmc85r7-nodejs
  janus-idp.io/tekton: ubpmc85r7-nodejs
  backstage.io/kubernetes-id: ubpmc85r7-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ubpmc85r7-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
